FROM debian:12-slim

RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
	&& localedef -i fr_FR -c -f UTF-8 -A /usr/share/locale/locale.alias fr_FR.UTF-8

ENV LANG fr_FR.utf8

RUN apt-get -y  install build-essential libssl-dev libffi-dev python3-dev\
	&& apt-get install -y python3 python3-pip \
	&& apt-get install -y python3-venv
RUN wget https://r.mariadb.com/downloads/mariadb_repo_setup \
	&& chmod +x mariadb_repo_setup \
	&& ./mariadb_repo_setup \
	--mariadb-server-version="mariadb-11.5.1" \
	&& apt-get install -y libmariadb3 libmariadb-dev


EXPOSE 5000

CMD ["/bin/bash"]